Test print branch

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -17,6 +17,7 @@ env:
   BUKET_TF_STATE: ${{ secrets.BUKET_TF_STATE }}
   EKS_CLUSTER: ${{ secrets.EKS_CLUSTER }}
   AWS_REGION: ${{ secrets.AWS_REGION }}
+  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
 
 permissions:
   id-token: write
@@ -64,15 +65,22 @@ jobs:
 
       - name: Terraform Validate
         id: validate
-        run: terraform validate
-
-      - name: Terraform Plan
-        id: plan
+        run: |
+          echo ${ BRANCH_NAME }
+          terraform validate
         
-        run: terraform plan -no-color -input=false -out planfile -var-file='stage.tfvars' -out=tfplan
-        continue-on-error: true
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan
+      #   id: plan
+        
+      #   run: terraform plan -no-color -input=false -out planfile -var-file='stage.tfvars' -out=tfplan
+      #   continue-on-error: true
 
+      # - name: Terraform plan status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      # - name: Terraform Apply
+      #   id: apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve input=false -parallelism=1 planfile
